version: '3.9'
services:
  pgsql:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host

volumes:
  pgsql_data:
