--CREATE SEQUENCE users_seq
--	INCREMENT BY 1
--	MINVALUE 1
--	MAXVALUE 9223372036854775807
--	START 1
--	CACHE 1
--	NO CYCLE;
--
--CREATE SEQUENCE tokens_seq
--	INCREMENT BY 1
--	MINVALUE 1
--	MAXVALUE 9223372036854775807
--	START 1
--	CACHE 1
--	NO CYCLE;
--
--CREATE SEQUENCE signing_requests_seq
--	INCREMENT BY 1
--	MINVALUE 1
--	MAXVALUE 9223372036854775807
--	START 1
--	CACHE 1
--	NO CYCLE;
--
--CREATE SEQUENCE documents_seq
--	INCREMENT BY 1
--	MINVALUE 1
--	MAXVALUE 9223372036854775807
--	START 1
--	CACHE 1
--	NO CYCLE;


CREATE TABLE users (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	email varchar(100) NOT NULL,
	firstname varchar(255) NOT NULL,
	lastname varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	"role" varchar(255) NULL,
	CONSTRAINT users_email_key UNIQUE (email),
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);

CREATE TABLE tokens (
	expired bool NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	revoked bool NOT NULL,
	user_id int8 NULL,
	"token" varchar(255) NULL,
	token_type varchar(255) NULL,
	CONSTRAINT tokens_pkey PRIMARY KEY (id),
	CONSTRAINT tokens_token_key UNIQUE (token),
	CONSTRAINT tokens_token_type_check CHECK (((token_type)::text = 'BEARER'::text))
);

CREATE TABLE signing_requests (
	is_signed bool NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	sign_date timestamptz(6) NULL,
	submission_date timestamptz(6) NULL,
	user_id int8 NULL,
	CONSTRAINT signing_requests_pkey PRIMARY KEY (id)
);

CREATE TABLE documents (
	is_confirmed bool NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	signing_request_id int8 NULL,
	file_name varchar(255) NOT NULL,
	file_content bytea NULL,
	CONSTRAINT documents_pkey PRIMARY KEY (id)
);







